#!/usr/bin/env python3
import psutil
import typer


app = typer.Typer()


@app.command()
def cpu():
    res = psutil.cpu_times_percent(interval=0.4)

    print('\nSample output:')
    for name, pecnet in res._asdict().items():
        print(f'system.cpu.{name} {pecnet}')


@app.command()
def mem():
    skip = {'percent', 'sout', 'sin', 'buffers', 'cached', 'slab'}
    svmem = psutil.virtual_memory()
    swap = psutil.swap_memory()

    print('\nSample output:')
    for name, size in svmem._asdict().items():
        if name in skip:
            continue
        print(f'virtual {name} {size}')

    for name, size in swap._asdict().items():
        if name in skip:
            continue
        print(f'swap {name} {size}')


if __name__ == '__main__':
    app()
